FROM node:12.18.1
ENV NODE_ENV=production

WORKDIR /app
COPY ["package.json", "package-lock.json*", "./"]

RUN npm config set strict-ssl false
RUN npm install --production

RUN npm install d3
RUN npm install d3-scale
RUN npm install d3-time
RUN npm install jquery
RUN npm install bootstrap

COPY . .

CMD [ "node", "server.js", "--public"]